"""Package entry point so the CLI runs with no console-script .exe shim.

``python -m okf_wiki <subcommand>`` is the portable invocation that works the
same on Windows and Linux. It avoids uv's generated ``okf-wiki.exe`` launcher
stub, which some Windows antivirus (e.g. Defender) quarantines on sight — the
stub is regenerated by every ``uv sync`` and re-blocked, so ``-m`` is the
reliable path. ``uv run python -m okf_wiki ingest`` is equivalent to
``uv run okf-wiki ingest`` but needs no executable.
"""

from __future__ import annotations

from .cli import main

if __name__ == "__main__":
    raise SystemExit(main())
